#!/usr/bin/env python

import sys
from motion_renderer.fake_motion_renderer_gui import FakeMotionRendererPlugin
from rqt_gui.main import Main

plugin = 'fake_motion_renderer'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
